### PR TITLE
Add docker integration

### PR DESCRIPTION
**Pull request by benjamin-thomas**
I wanted to try out your tool, but I'm a linux user so docker seems to be a good fit.

This setup seems sound, but being unfamiliar with Haskell, I'm not sure if that's the case as I keep getting `Unused found no results` from the tool (tested with several repos after creating tags per the README)

What do you think?

### CODE REVIEW

**Comment by joshuaclayton** [comment]
@benjamin-thomas thanks for putting this together!

I'll have to play around the Docker bit - since I'm also a self-proclaimed newbie to Docker for the most part, I'll be sure to take notes of the process and let you know if I run into any issues.

Somewhat related to this - I've been working on getting the library to a place where it has no dependencies and should be runnable as a binary. If I were to upload the binary to the releases, would that be an easier way for you to use it?

**Comment by benjamin-thomas** [comment]
Sure, a binary sounds great!

Let me know if you need some help with the docker stuff.

**Comment by joshuaclayton** [comment]
@benjamin-thomas thanks for your patience with this. I just finalized https://github.com/joshuaclayton/unused/releases/tag/v0.6.1.1 and included the binary. As I mentioned, one of the goals was to ensure there were no platform-specific dependencies, so I *think* this should work for you. Let me know how it goes!

**Comment by benjamin-thomas** [comment]
Hello @joshuaclayton, thanks for the follow up.

I assumed you had cross compilation in mind.

Unless I misunderstand something, the binary available in the release is Mac specific, and so I can't use it on my Linux dev machine.

    benjamin@dev:~/Downloads/$ file unused
    unused: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>

**Comment by joshuaclayton** [comment]
@benjamin-thomas ah, yep, my fault. I've not done any cross-compilation work so I wasn't sure if/how it'd go.

As for Docker, I went through and was able to compile it correctly it looks like. However, I threw the script in a file (which runs fine) but I always see the "no results" message you'd posted about, even when there are results with the installed version I have. I copied it verbatim, should there be part of that I should tailor to my machine?

```
cat ~/bin/unused2
docker run --rm -it -v $(pwd):/code local/unused unused $@
```

**Comment by joshuaclayton** [comment]
@benjamin-thomas also, I updated the filename of the binary to mention so it's more clear the platform it's built for

**Comment by benjamin-thomas** [comment]
Hi @joshuaclayton.

At this point, I think a few debug statements here and there could provide more information. Unfortunately, Haskell looks pretty alien to me so I'm not sure where to start.

However, I can explain to you in further details what happens with the docker setup.

First of all, the docker container is an independent process that will be launched, and killed each time the tool is ran.

This docker container needs to access to the code on our file system, so 2 things need to happen:

1. I "declare" the container's working directory as `/code` via the Dockerfile
2. Each time the container is launched, we need to "mount" our `$PWD` to the container's `/code` file system.

So let me explain the following command:

    docker run --rm -it -v $(pwd):/code local/unused ls

- The docker client asks the docker daemon to create a container process, then remove it on exit via the `--rm`.
- Since this is not a background process, we declare this process as "interactive" with `-it`
- We indicate we will use the `local/unused` image we built via the Dockerfile.
- To give the containers access to our code we "mount" our current directory to the container's `/code` path.
- We run the `ls` command inside our container: this will list the files we just mounted.
- On exit, the container is destroyed.

As an example, we could do this:

    docker run --rm -it -v $(pwd):/code local/unused ag -B1 -A3 Gemfile --depth 3

Note: after making a code change to unused, we need to rebuild the docker image if we want those changes propagated to the docker run script.

Hope that helps

**Comment by joshuaclayton** [comment]
@benjamin-thomas understood on the debugging. There are hacky ways to introduce it, but it's been on my list of things to do for a while now, and I think it should be relatively easy to introduce some sort of variable verbosity (I'd played around with this [here](https://github.com/joshuaclayton/file-fun/pull/1/files), actually).

After doing some debugging, though, I seem to have tracked down the issue.

I ran `docker run --rm -it -v $(pwd):/code local/unused ag --version`, which reported 0.26. After playing around with some `ag` commands within docker, I realized it was missing the ability to return counts, which led me to:

https://github.com/ggreer/the_silver_searcher/commit/ce68e51c71c7a178402126beb327423445823db1

So, it looks like the version of `ag` isn't up-to-date on the image. Is there a way to do that?

From an OS X perspective, I'll look at validating minimum required version of ag to be 0.27 (where `--count/-c` was introduced) and update the README as well.

**Comment by benjamin-thomas** [comment]
Got you, I'll update the Dockerfile by introducing a compilation step in
order to acquire the latest ag.
Le dim. 16 oct. 2016 à 13:32, Josh Clayton <notifications@github.com> a
écrit :

**Comment by benjamin-thomas** [comment]
Hello @joshuaclayton.

I updated the Dockerfile: the tool does return output now (yay!).

On a side note, as a user, the build step could be skipped if you would provide an image that would get synced with your repo (automated build).

I can give you more details if you're interested.

**Comment by joshuaclayton** [comment]
@benjamin-thomas that's great news!

I'd love to hear about the automated build process. If I go the Homebrew-supported path, it still misses any Linux users; assuming support "costs" are low (given my unfamiliarity), I'd definitely love help.

**Comment by benjamin-thomas** [comment]
Hello @joshuaclayton 

You can create an "automated build" freely by creating an account on hub.docker.com.

Here I demonstrate the steps necessary from my docker hub account (bthomas) and point to my github repo.

1. Create an "Automated Build"
image

2. Link your github account, then select your repo
image

3. Trigger manually or push
image

4. Building
image

5. Once built, anyone can run the following command

```bash
docker run --rm -v $(pwd):/code bthomas/unused unused
```

This will download the image from the docker hub, thus providing a working version of the software.

At that point, I feel it's best to setup a bash script (as a user) to launch the docker command more easily.

Your image will be rebuilt on every code push, or when the underlying base image gets updated.

**Comment by joshuaclayton** [comment]
@benjamin-thomas you are awesome, thank you for your work on this! I'll be digging in the next couple of days (last night/this morning was spent on other things!) to move this forward.

**Comment by benjamin-thomas** [comment]
No problem :)

**Comment by joshuaclayton** [comment]
@benjamin-thomas Thank you so much for your help. I've merged this as 9248aa929dd7880ec4a34e68937e6ab7c025aa9d, and I'm all set up on hub.docker.com: https://hub.docker.com/r/joshuaclayton/unused/

🎉

**Comment by benjamin-thomas** [comment]
Yeeeah :tada: ;)

I forgot to mention but, as it is, piping from stdin does not work if I recall correctly, but this is probably only a minor issue for now (I'll look into it if it's a problem).

**Pull request closed without merging**
