### PR TITLE
more newbie- and intermediate-friendly instructions

### PR DESCRIPTION
**Pull request by josephgrossberg**
Not sure where these should go; this PR is mostly to start discussion. TY @joshuaclayton for a helpful tool!

### CODE REVIEW

**Comment by joshuaclayton** [comment]
Related: https://github.com/joshuaclayton/homebrew-formulae/commit/aca4461383eaa0098e317d34fdb6aa3efd323a37

**Comment by joshuaclayton** [comment]
@josephgrossberg I'm not sure how best to have each of us work on changes on the same branch, so I created a new PR with a few minor edits (one involving the updated wording now that I've added ctags as a dependency in Homebrew) at https://github.com/joshuaclayton/unused/pull/67. Let me know what you think! I attempted to introduce a more repeatable pattern for auto-generating ctags by pointing people to [the Tim Pope article](http://tbaggery.com/2011/08/08/effortless-ctags-with-git.html), which I also actually cover [if no tags file is found](https://github.com/joshuaclayton/unused/blob/8b50f5dd686529d91cc2567754f5444d31af69cd/src/Unused/CLI/Views/MissingTagsFileError.hs#L35).

Thoughts?

**Comment by josephgrossberg** [comment]
I think the Pope article is neither "Effortless" (at least the setup) nor newbie-friendly.

Compare all his steps, and the complexity of something like this:

```sh
#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
git ls-files | \
  ctags --tag-relative -L - -f"$dir/$$.tags" --languages=-javascript,sql
mv "$dir/$$.tags" "$dir/tags"
```

versus, say:

```
$ git ls-files | xargs ctags
$ unused -a
```

Maybe a project wiki page for newbies?

**Comment by joshuaclayton** [comment]
@josephgrossberg I definitely see what you're saying - there's a lot going on there. I think the "effortless" was focused more on "once you set this up, it's good to go."

My concern with suggesting people manually call ctags is that it requires people remember to do so prior to using `unused`.

Thinking about it now, I wonder if we could have troubleshooting contain two sections - one for getting ctags installed and working, and another for addressing the automation aspect by suggesting people follow tpope's article. Thoughts on that separation?

**Comment by josephgrossberg** [comment]
I like that idea, the two sections. Closing PR.

**Comment by josephgrossberg** [comment]
Please feel free to @-mention me when you update the README, and I'll try to view it from two perspectives:

* I've never used ctags before; how can I use this?
* I'm familiar with ctags and would like to incorporate this into my workflow

**Pull request closed without merging**
